@VoteBem_HostAddress = http://localhost:5253

GET {{VoteBem_HostAddress}}/candidatos/all-paginated?pageNumber=1&pageSize=10
Accept: application/json
###

GET {{VoteBem_HostAddress}}/candidatos/by-name-paginated?name=lula
Accept: application/json

### 
GET {{VoteBem_HostAddress}}/candidatos/by-partido-paginated?partido=pt
Accept: application/json

### 
GET {{VoteBem_HostAddress}}/candidatos/by-ano-eleitoral-paginated?ano=2022
Accept: application/json

### 
  GET {{VoteBem_HostAddress}}/candidatos/profile?nrCpfCandidato=07068093868
  Accept: application/json